export const GET_POKEMONS = "GET_POKEMONS";
export const GET_POKEMON = "GET_POKEMON";
export const GET_MY_POKEMONS = "GET_MY_POKEMONS";
export const CHECK_PROBABILITY = "CHECK_PROBABILITY";
export const CATCH_POKEMON = "CATCH_POKEMON";
export const CHECK_PRIME = "CHECK_PRIME";
export const RELEASE_POKEMON = "RELEASE_POKEMON";
export const RENAME_POKEMON = "RENAME_POKEMON";
